### ISSUE TITLE
Path parameter doesn't work with @authorize decorator

### ISSUE THREAD

**Issue by julyvee** [Mimetis/aad_fastapi#9]
**Describe the bug**
When I create a fastapi endpoint with a path parameter, it works fine until I add the @authorize decorator, then I suddenly get this error:

`TypeError: read_item() got multiple values for argument 'item_id'`

![Screenshot 2023-07-20 at 14 15 02](https://github.com/Mimetis/aad_fastapi/assets/10207075/d7347b97-63f1-4bf6-96c5-aa50eec88ab1)

The original endpoint code for this test endpoint is:

```python
@app.get("/items/{item_id}")
@authorize("user_impersonation")
def read_item(
    item_id: int, request: Request, token=Depends(oauth2_scheme(options=api_options))
):
    return {"item_id": item_id, "user": request.user}
```

**To Reproduce**
1. Create endpoint with path parameter
2. Add @authorize decorator to endpoint
3. Run the API
4. Test the endpoint through /docs swagger page
5. Receive 500 Internal server error
6. See details in console where the API is running

**Expected behavior**
The endpoint returns the result including the path parameter without producing an error.

**Additional context**
Running in ubuntu devcontainer

**Comment by dorlugasigal** [comment]
Hey @julyvee, thanks for contributing :)
a workaround you can use so you can keep using this library until this is fixed:
place the `Request` parameter first, and then all the other params, 

```
@app.get("/items/{item_id}")
@authorize("MyScope")
def read_item(
     request: Request, item_id: int, token=Depends(oauth2_scheme(options=api_options))
):
    return {"item_id": item_id, "user": request.user}
```
I will keep this issue open until it is documented

BTW, this behavior is [a limitation we had because of `starlette.authentication` `requires` decorator](https://github.com/encode/starlette/blob/master/starlette/authentication.py#L37), which requires to have a request explicitly as a param, which restricts us with the position of the param

**Comment by julyvee** [comment]
Thank you @dorlugasigal. I can confirm that changing the order works!
